export const colorMap : PokemonColorMap = {
    fire: '#ff4d26',
    water: '#3aa4ff',
    grass: '#82d35f',
    electric: '#ffd33a',
    flying: '#93a4ff',
    normal: '#b3b3a3',
    psychic: '#ff60a3',
    ice: '#71d2ff',
    bug: '#b3c326',
    rock: '#c3b371',
    ground: '#e1c35f',
    fairy: '#f0a3f0',
    poison: '#b35fa3',
    fighting: '#c3604d',
    ghost: '#7171c3',
    steel: '#b3b3c3',
    dark: '#825f4d',
    dragon: '#8271f0',
}

export const pokemonList: Array<Pokemon> = [
    {
        id: 1,
        name: 'bulbasaur',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/1.png'),
    },
    {
        id: 2,
        name: 'ivysaur',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/2.png'),
    },
    {
        id: 3,
        name: 'venusaur',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/3.png'),
    },
    {
        id: 4,
        name: 'charmander',
        types: ['fire'],
        image: require('../assets/sprites/4.png'),
    },
    {
        id: 5,
        name: 'charmeleon',
        types: ['fire'],
        image: require('../assets/sprites/5.png'),
    },
    {
        id: 6,
        name: 'charizard',
        types: ['flying', 'fire'],
        image: require('../assets/sprites/6.png'),
    },
    {
        id: 7,
        name: 'squirtle',
        types: ['water'],
        image: require('../assets/sprites/7.png'),
    },
    {
        id: 8,
        name: 'wartortle',
        types: ['water'],
        image: require('../assets/sprites/8.png'),
    },
    {
        id: 9,
        name: 'blastoise',
        types: ['water'],
        image: require('../assets/sprites/9.png'),
    },
    {
        id: 10,
        name: 'caterpie',
        types: ['bug'],
        image: require('../assets/sprites/10.png'),
    },
    {
        id: 11,
        name: 'metapod',
        types: ['bug'],
        image: require('../assets/sprites/11.png'),
    },
    {
        id: 12,
        name: 'butterfree',
        types: ['flying', 'bug'],
        image: require('../assets/sprites/12.png'),
    },
    {
        id: 13,
        name: 'weedle',
        types: ['poison', 'bug'],
        image: require('../assets/sprites/13.png'),
    },
    {
        id: 14,
        name: 'kakuna',
        types: ['poison', 'bug'],
        image: require('../assets/sprites/14.png'),
    },
    {
        id: 15,
        name: 'beedrill',
        types: ['poison', 'bug'],
        image: require('../assets/sprites/15.png'),
    },
    {
        id: 16,
        name: 'pidgey',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/16.png'),
    },
    {
        id: 17,
        name: 'pidgeotto',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/17.png'),
    },
    {
        id: 18,
        name: 'pidgeot',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/18.png'),
    },
    {
        id: 19,
        name: 'rattata',
        types: ['normal'],
        image: require('../assets/sprites/19.png'),
    },
    {
        id: 20,
        name: 'raticate',
        types: ['normal'],
        image: require('../assets/sprites/20.png'),
    },
    {
        id: 21,
        name: 'spearow',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/21.png'),
    },
    {
        id: 22,
        name: 'fearow',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/22.png'),
    },
    {
        id: 23,
        name: 'ekans',
        types: ['poison'],
        image: require('../assets/sprites/23.png'),
    },
    {
        id: 24,
        name: 'arbok',
        types: ['poison'],
        image: require('../assets/sprites/24.png'),
    },
    {
        id: 25,
        name: 'pikachu',
        types: ['electric'],
        image: require('../assets/sprites/25.png'),
    },
    {
        id: 26,
        name: 'raichu',
        types: ['electric'],
        image: require('../assets/sprites/26.png'),
    },
    {
        id: 27,
        name: 'sandshrew',
        types: ['ground'],
        image: require('../assets/sprites/27.png'),
    },
    {
        id: 28,
        name: 'sandslash',
        types: ['ground'],
        image: require('../assets/sprites/28.png'),
    },
    {
        id: 29,
        name: 'nidoran-f',
        types: ['poison'],
        image: require('../assets/sprites/29.png'),
    },
    {
        id: 30,
        name: 'nidorina',
        types: ['poison'],
        image: require('../assets/sprites/30.png'),
    },
    {
        id: 31,
        name: 'nidoqueen',
        types: ['ground', 'poison'],
        image: require('../assets/sprites/31.png'),
    },
    {
        id: 32,
        name: 'nidoran-m',
        types: ['poison'],
        image: require('../assets/sprites/32.png'),
    },
    {
        id: 33,
        name: 'nidorino',
        types: ['poison'],
        image: require('../assets/sprites/33.png'),
    },
    {
        id: 34,
        name: 'nidoking',
        types: ['ground', 'poison'],
        image: require('../assets/sprites/34.png'),
    },
    {
        id: 35,
        name: 'clefairy',
        types: ['fairy'],
        image: require('../assets/sprites/35.png'),
    },
    {
        id: 36,
        name: 'clefable',
        types: ['fairy'],
        image: require('../assets/sprites/36.png'),
    },
    {
        id: 37,
        name: 'vulpix',
        types: ['fire'],
        image: require('../assets/sprites/37.png'),
    },
    {
        id: 38,
        name: 'ninetales',
        types: ['fire'],
        image: require('../assets/sprites/38.png'),
    },
    {
        id: 39,
        name: 'jigglypuff',
        types: ['fairy', 'normal'],
        image: require('../assets/sprites/39.png'),
    },
    {
        id: 40,
        name: 'wigglytuff',
        types: ['fairy', 'normal'],
        image: require('../assets/sprites/40.png'),
    },
    {
        id: 41,
        name: 'zubat',
        types: ['flying', 'poison'],
        image: require('../assets/sprites/41.png'),
    },
    {
        id: 42,
        name: 'golbat',
        types: ['flying', 'poison'],
        image: require('../assets/sprites/42.png'),
    },
    {
        id: 43,
        name: 'oddish',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/43.png'),
    },
    {
        id: 44,
        name: 'gloom',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/44.png'),
    },
    {
        id: 45,
        name: 'vileplume',
        types: ['grass', 'poison'],
        image: require('../assets/sprites/45.png'),
    },
    {
        id: 46,
        name: 'paras',
        types: ['grass', 'bug'],
        image: require('../assets/sprites/46.png'),
    },
    {
        id: 47,
        name: 'parasect',
        types: ['grass', 'bug'],
        image: require('../assets/sprites/47.png'),
    },
    {
        id: 48,
        name: 'venonat',
        types: ['poison', 'bug'],
        image: require('../assets/sprites/48.png'),
    },
    {
        id: 49,
        name: 'venomoth',
        types: ['poison', 'bug'],
        image: require('../assets/sprites/49.png'),
    },
    {
        id: 50,
        name: 'diglett',
        types: ['ground'],
        image: require('../assets/sprites/50.png'),
    },
    {
        id: 51,
        name: 'dugtrio',
        types: ['ground'],
        image: require('../assets/sprites/51.png'),
    },
    {
        id: 52,
        name: 'meowth',
        types: ['normal'],
        image: require('../assets/sprites/52.png'),
    },
    {
        id: 53,
        name: 'persian',
        types: ['normal'],
        image: require('../assets/sprites/53.png'),
    },
    {
        id: 54,
        name: 'psyduck',
        types: ['water'],
        image: require('../assets/sprites/54.png'),
    },
    {
        id: 55,
        name: 'golduck',
        types: ['water'],
        image: require('../assets/sprites/55.png'),
    },
    {
        id: 56,
        name: 'mankey',
        types: ['fighting'],
        image: require('../assets/sprites/56.png'),
    },
    {
        id: 57,
        name: 'primeape',
        types: ['fighting'],
        image: require('../assets/sprites/57.png'),
    },
    {
        id: 58,
        name: 'growlithe',
        types: ['fire'],
        image: require('../assets/sprites/58.png'),
    },
    {
        id: 59,
        name: 'arcanine',
        types: ['fire'],
        image: require('../assets/sprites/59.png'),
    },
    {
        id: 60,
        name: 'poliwag',
        types: ['water'],
        image: require('../assets/sprites/60.png'),
    },
    {
        id: 61,
        name: 'poliwhirl',
        types: ['water'],
        image: require('../assets/sprites/61.png'),
    },
    {
        id: 62,
        name: 'poliwrath',
        types: ['fighting', 'water'],
        image: require('../assets/sprites/62.png'),
    },
    {
        id: 63,
        name: 'abra',
        types: ['psychic'],
        image: require('../assets/sprites/63.png'),
    },
    {
        id: 64,
        name: 'kadabra',
        types: ['psychic'],
        image: require('../assets/sprites/64.png'),
    },
    {
        id: 65,
        name: 'alakazam',
        types: ['psychic'],
        image: require('../assets/sprites/65.png'),
    },
    {
        id: 66,
        name: 'machop',
        types: ['fighting'],
        image: require('../assets/sprites/66.png'),
    },
    {
        id: 67,
        name: 'machoke',
        types: ['fighting'],
        image: require('../assets/sprites/67.png'),
    },
    {
        id: 68,
        name: 'machamp',
        types: ['fighting'],
        image: require('../assets/sprites/68.png'),
    },
    {
        id: 69,
        name: 'bellsprout',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/69.png'),
    },
    {
        id: 70,
        name: 'weepinbell',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/70.png'),
    },
    {
        id: 71,
        name: 'victreebel',
        types: ['poison', 'grass'],
        image: require('../assets/sprites/71.png'),
    },
    {
        id: 72,
        name: 'tentacool',
        types: ['poison', 'water'],
        image: require('../assets/sprites/72.png'),
    },
    {
        id: 73,
        name: 'tentacruel',
        types: ['poison', 'water'],
        image: require('../assets/sprites/73.png'),
    },
    {
        id: 74,
        name: 'geodude',
        types: ['ground', 'rock'],
        image: require('../assets/sprites/74.png'),
    },
    {
        id: 75,
        name: 'graveler',
        types: ['ground', 'rock'],
        image: require('../assets/sprites/75.png'),
    },
    {
        id: 76,
        name: 'golem',
        types: ['ground', 'rock'],
        image: require('../assets/sprites/76.png'),
    },
    {
        id: 77,
        name: 'ponyta',
        types: ['fire'],
        image: require('../assets/sprites/77.png'),
    },
    {
        id: 78,
        name: 'rapidash',
        types: ['fire'],
        image: require('../assets/sprites/78.png'),
    },
    {
        id: 79,
        name: 'slowpoke',
        types: ['psychic', 'water'],
        image: require('../assets/sprites/79.png'),
    },
    {
        id: 80,
        name: 'slowbro',
        types: ['psychic', 'water'],
        image: require('../assets/sprites/80.png'),
    },
    {
        id: 81,
        name: 'magnemite',
        types: ['steel', 'electric'],
        image: require('../assets/sprites/81.png'),
    },
    {
        id: 82,
        name: 'magneton',
        types: ['steel', 'electric'],
        image: require('../assets/sprites/82.png'),
    },
    {
        id: 83,
        name: 'farfetchd',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/83.png'),
    },
    {
        id: 84,
        name: 'doduo',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/84.png'),
    },
    {
        id: 85,
        name: 'dodrio',
        types: ['flying', 'normal'],
        image: require('../assets/sprites/85.png'),
    },
    {
        id: 86,
        name: 'seel',
        types: ['water'],
        image: require('../assets/sprites/86.png'),
    },
    {
        id: 87,
        name: 'dewgong',
        types: ['ice', 'water'],
        image: require('../assets/sprites/87.png'),
    },
    {
        id: 88,
        name: 'grimer',
        types: ['poison'],
        image: require('../assets/sprites/88.png'),
    },
    {
        id: 89,
        name: 'muk',
        types: ['poison'],
        image: require('../assets/sprites/89.png'),
    },
    {
        id: 90,
        name: 'shellder',
        types: ['water'],
        image: require('../assets/sprites/90.png'),
    },
    {
        id: 91,
        name: 'cloyster',
        types: ['ice', 'water'],
        image: require('../assets/sprites/91.png'),
    },
    {
        id: 92,
        name: 'gastly',
        types: ['poison', 'ghost'],
        image: require('../assets/sprites/92.png'),
    },
    {
        id: 93,
        name: 'haunter',
        types: ['poison', 'ghost'],
        image: require('../assets/sprites/93.png'),
    },
    {
        id: 94,
        name: 'gengar',
        types: ['poison', 'ghost'],
        image: require('../assets/sprites/94.png'),
    },
    {
        id: 95,
        name: 'onix',
        types: ['ground', 'rock'],
        image: require('../assets/sprites/95.png'),
    },
    {
        id: 96,
        name: 'drowzee',
        types: ['psychic'],
        image: require('../assets/sprites/96.png'),
    },
    {
        id: 97,
        name: 'hypno',
        types: ['psychic'],
        image: require('../assets/sprites/97.png'),
    },
    {
        id: 98,
        name: 'krabby',
        types: ['water'],
        image: require('../assets/sprites/98.png'),
    },
    {
        id: 99,
        name: 'kingler',
        types: ['water'],
        image: require('../assets/sprites/99.png'),
    },
    {
        id: 100,
        name: 'voltorb',
        types: ['electric'],
        image: require('../assets/sprites/100.png'),
    },
    {
        id: 101,
        name: 'electrode',
        types: ['electric'],
        image: require('../assets/sprites/101.png'),
    },
    {
        id: 102,
        name: 'exeggcute',
        types: ['psychic', 'grass'],
        image: require('../assets/sprites/102.png'),
    },
    {
        id: 103,
        name: 'exeggutor',
        types: ['psychic', 'grass'],
        image: require('../assets/sprites/103.png'),
    },
    {
        id: 104,
        name: 'cubone',
        types: ['ground'],
        image: require('../assets/sprites/104.png'),
    },
    {
        id: 105,
        name: 'marowak',
        types: ['ground'],
        image: require('../assets/sprites/105.png'),
    },
    {
        id: 106,
        name: 'hitmonlee',
        types: ['fighting'],
        image: require('../assets/sprites/106.png'),
    },
    {
        id: 107,
        name: 'hitmonchan',
        types: ['fighting'],
        image: require('../assets/sprites/107.png'),
    },
    {
        id: 108,
        name: 'lickitung',
        types: ['normal'],
        image: require('../assets/sprites/108.png'),
    },
    {
        id: 109,
        name: 'koffing',
        types: ['poison'],
        image: require('../assets/sprites/109.png'),
    },
    {
        id: 110,
        name: 'weezing',
        types: ['poison'],
        image: require('../assets/sprites/110.png'),
    },
    {
        id: 111,
        name: 'rhyhorn',
        types: ['rock', 'ground'],
        image: require('../assets/sprites/111.png'),
    },
    {
        id: 112,
        name: 'rhydon',
        types: ['rock', 'ground'],
        image: require('../assets/sprites/112.png'),
    },
    {
        id: 113,
        name: 'chansey',
        types: ['normal'],
        image: require('../assets/sprites/113.png'),
    },
    {
        id: 114,
        name: 'tangela',
        types: ['grass'],
        image: require('../assets/sprites/114.png'),
    },
    {
        id: 115,
        name: 'kangaskhan',
        types: ['normal'],
        image: require('../assets/sprites/115.png'),
    },
    {
        id: 116,
        name: 'horsea',
        types: ['water'],
        image: require('../assets/sprites/116.png'),
    },
    {
        id: 117,
        name: 'seadra',
        types: ['water'],
        image: require('../assets/sprites/117.png'),
    },
    {
        id: 118,
        name: 'goldeen',
        types: ['water'],
        image: require('../assets/sprites/118.png'),
    },
    {
        id: 119,
        name: 'seaking',
        types: ['water'],
        image: require('../assets/sprites/119.png'),
    },
    {
        id: 120,
        name: 'staryu',
        types: ['water'],
        image: require('../assets/sprites/120.png'),
    },
    {
        id: 121,
        name: 'starmie',
        types: ['psychic', 'water'],
        image: require('../assets/sprites/121.png'),
    },
    {
        id: 122,
        name: 'mr-mime',
        types: ['fairy', 'psychic'],
        image: require('../assets/sprites/122.png'),
    },
    {
        id: 123,
        name: 'scyther',
        types: ['flying', 'bug'],
        image: require('../assets/sprites/123.png'),
    },
    {
        id: 124,
        name: 'jynx',
        types: ['psychic', 'ice'],
        image: require('../assets/sprites/124.png'),
    },
    {
        id: 125,
        name: 'electabuzz',
        types: ['electric'],
        image: require('../assets/sprites/125.png'),
    },
    {
        id: 126,
        name: 'magmar',
        types: ['fire'],
        image: require('../assets/sprites/126.png'),
    },
    {
        id: 127,
        name: 'pinsir',
        types: ['bug'],
        image: require('../assets/sprites/127.png'),
    },
    {
        id: 128,
        name: 'tauros',
        types: ['normal'],
        image: require('../assets/sprites/128.png'),
    },
    {
        id: 129,
        name: 'magikarp',
        types: ['water'],
        image: require('../assets/sprites/129.png'),
    },
    {
        id: 130,
        name: 'gyarados',
        types: ['flying', 'water'],
        image: require('../assets/sprites/130.png'),
    },
    {
        id: 131,
        name: 'lapras',
        types: ['ice', 'water'],
        image: require('../assets/sprites/131.png'),
    },
    {
        id: 132,
        name: 'ditto',
        types: ['normal'],
        image: require('../assets/sprites/132.png'),
    },
    {
        id: 133,
        name: 'eevee',
        types: ['normal'],
        image: require('../assets/sprites/133.png'),
    },
    {
        id: 134,
        name: 'vaporeon',
        types: ['water'],
        image: require('../assets/sprites/134.png'),
    },
    {
        id: 135,
        name: 'jolteon',
        types: ['electric'],
        image: require('../assets/sprites/135.png'),
    },
    {
        id: 136,
        name: 'flareon',
        types: ['fire'],
        image: require('../assets/sprites/136.png'),
    },
    {
        id: 137,
        name: 'porygon',
        types: ['normal'],
        image: require('../assets/sprites/137.png'),
    },
    {
        id: 138,
        name: 'omanyte',
        types: ['water', 'rock'],
        image: require('../assets/sprites/138.png'),
    },
    {
        id: 139,
        name: 'omastar',
        types: ['water', 'rock'],
        image: require('../assets/sprites/139.png'),
    },
    {
        id: 140,
        name: 'kabuto',
        types: ['water', 'rock'],
        image: require('../assets/sprites/140.png'),
    },
    {
        id: 141,
        name: 'kabutops',
        types: ['water', 'rock'],
        image: require('../assets/sprites/141.png'),
    },
    {
        id: 142,
        name: 'aerodactyl',
        types: ['flying', 'rock'],
        image: require('../assets/sprites/142.png'),
    },
    {
        id: 143,
        name: 'snorlax',
        types: ['normal'],
        image: require('../assets/sprites/143.png'),
    },
    {
        id: 144,
        name: 'articuno',
        types: ['flying', 'ice'],
        image: require('../assets/sprites/144.png'),
    },
    {
        id: 145,
        name: 'zapdos',
        types: ['flying', 'electric'],
        image: require('../assets/sprites/145.png'),
    },
    {
        id: 146,
        name: 'moltres',
        types: ['flying', 'fire'],
        image: require('../assets/sprites/146.png'),
    },
    {
        id: 147,
        name: 'dratini',
        types: ['dragon'],
        image: require('../assets/sprites/147.png'),
    },
    {
        id: 148,
        name: 'dragonair',
        types: ['dragon'],
        image: require('../assets/sprites/148.png'),
    },
    {
        id: 149,
        name: 'dragonite',
        types: ['flying', 'dragon'],
        image: require('../assets/sprites/149.png'),
    },
    {
        id: 150,
        name: 'mewtwo',
        types: ['psychic'],
        image: require('../assets/sprites/150.png'),
    },
    {
        id: 151,
        name: 'mew',
        types: ['psychic'],
        image: require('../assets/sprites/151.png'),
    },
    {
        id: 201,
        name: 'unown',
        types: ['?'],
        image: require('../assets/sprites/201.png'),
    },
]
